spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:postgresql://${HOST}:15432/${POSTGRES_DATABASE}?currentSchema=tasklist
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

security:
  jwt:
    secret: ${SECURITY_SECRET}
    access: ${SECURITY_ACCESS}
    refresh: ${SECURITY_REFRESH}

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

